DROP DATABASE IF EXISTS restdb;
DROP ROLE IF EXISTS restadmin;

CREATE DATABASE restdb WITH ENCODING 'UTF8' TEMPLATE template0;
CREATE ROLE restadmin WITH PASSWORD 'password';

GRANT ALL PRIVILEGES ON DATABASE restdb TO restadmin;
ALTER DATABASE restdb OWNER TO restadmin;
ALTER ROLE restadmin WITH LOGIN;
